exclude-pos-list:
  - ["副詞", "助詞類接続"]
  - ["助詞"]
  - ["助動詞"]
  - ["記号"]
  - ["連体詞"]
  - ["副詞", "助詞類接続"]
  - ["動詞", "非自立"]
  - ["動詞", "接尾"]
  - ["名詞", "代名詞"]
  - ["名詞", "非自立"]
  - ["名詞", "接尾"]
  - ["名詞", "数"]
  - ["名詞", "サ変接続"]
  - ["フィラー"]

keep-pos-list:
  - ["名詞"]
  - ["カスタム名詞"]

stop-words:
  - "ある"
  - "ない"
  - "いい"
  - "よく"
  - "どう"
  - "あっ"
  - "し"
  - "する"
  - "なる"
  - "できる"

threshold: 3

user-dict:
  - "日本経済新聞,日本 経済 新聞,ニホン ケイザイ シンブン,カスタム名詞"
  - "関西国際空港,関西 国際 空港,カンサイ コクサイ クウコウ,カスタム名詞"
  - "インターフェイス,インターフェイス,インターフェイス,カスタム名詞"
  - "ユースケース,ユースケース,ユースケース,カスタム名詞"
  - "ロードマップ,ロードマップ,ロードマップ,カスタム名詞"
